# Generated by Django 5.2.5 on 2025-08-22 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subdomain', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speed', models.CharField(blank=True, max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('interactive_tv', models.BooleanField(default=False, verbose_name='Интерактивное ТВ')),
                ('online_cinema', models.BooleanField(default=False, verbose_name='Онлайн кинотеатр')),
                ('mobile_data', models.PositiveIntegerField(default=0, verbose_name='Мобильные данные (ГБ)')),
                ('mobile_minutes', models.PositiveIntegerField(default=0, verbose_name='Мобильные минуты')),
                ('mobile_sms', models.PositiveIntegerField(default=0, verbose_name='Мобильные СМС')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='tariffs.region')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес подключения')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('repeated', 'Повторное обращение'), ('no_tech', 'Нет технической возможности'), ('transferred', 'Передано провайдеру')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('installation_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата монтажа')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('is_transferred_to_telegram', models.BooleanField(default=False, verbose_name='Передано в Telegram')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffs.region', verbose_name='Регион')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariffs.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
